services:
  db:
    image: postgres:16
    container_name: docker-todo-db
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass123
      POSTGRES_DB: todo_db
    ports:
      - "8888:5432"
    volumes:
      - todo-data:/var/lib/postgresql/data

volumes:
  todo-data: